/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 53
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 37
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 8
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  anon_sym_Table = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_LBRACK = 5,
  anon_sym_COMMA = 6,
  anon_sym_RBRACK = 7,
  anon_sym_pk = 8,
  anon_sym_unique = 9,
  anon_sym_increment = 10,
  anon_sym_notnull = 11,
  anon_sym_Ref = 12,
  anon_sym_ref = 13,
  anon_sym_COLON = 14,
  aux_sym_inline_ref_token1 = 15,
  anon_sym_GT = 16,
  anon_sym_LT = 17,
  anon_sym_DASH = 18,
  anon_sym_DOT = 19,
  anon_sym_Enum = 20,
  sym_identifier = 21,
  sym_source_file = 22,
  sym_table_definition = 23,
  sym_column_definition = 24,
  sym_attribute_block = 25,
  sym_attribute = 26,
  sym_attribute_keyword = 27,
  sym_inline_ref = 28,
  sym_ref_definition = 29,
  sym_ref_path = 30,
  sym_enum_definition = 31,
  sym_enum_value = 32,
  aux_sym_source_file_repeat1 = 33,
  aux_sym_table_definition_repeat1 = 34,
  aux_sym_attribute_block_repeat1 = 35,
  aux_sym_enum_definition_repeat1 = 36,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_Table] = "Table",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_pk] = "pk",
  [anon_sym_unique] = "unique",
  [anon_sym_increment] = "increment",
  [anon_sym_notnull] = "not null",
  [anon_sym_Ref] = "Ref",
  [anon_sym_ref] = "ref",
  [anon_sym_COLON] = ":",
  [aux_sym_inline_ref_token1] = "inline_ref_token1",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_DASH] = "-",
  [anon_sym_DOT] = ".",
  [anon_sym_Enum] = "Enum",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym_table_definition] = "table_definition",
  [sym_column_definition] = "column_definition",
  [sym_attribute_block] = "attribute_block",
  [sym_attribute] = "attribute",
  [sym_attribute_keyword] = "attribute_keyword",
  [sym_inline_ref] = "inline_ref",
  [sym_ref_definition] = "ref_definition",
  [sym_ref_path] = "ref_path",
  [sym_enum_definition] = "enum_definition",
  [sym_enum_value] = "enum_value",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_table_definition_repeat1] = "table_definition_repeat1",
  [aux_sym_attribute_block_repeat1] = "attribute_block_repeat1",
  [aux_sym_enum_definition_repeat1] = "enum_definition_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_Table] = anon_sym_Table,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_pk] = anon_sym_pk,
  [anon_sym_unique] = anon_sym_unique,
  [anon_sym_increment] = anon_sym_increment,
  [anon_sym_notnull] = anon_sym_notnull,
  [anon_sym_Ref] = anon_sym_Ref,
  [anon_sym_ref] = anon_sym_ref,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_inline_ref_token1] = aux_sym_inline_ref_token1,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_Enum] = anon_sym_Enum,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym_table_definition] = sym_table_definition,
  [sym_column_definition] = sym_column_definition,
  [sym_attribute_block] = sym_attribute_block,
  [sym_attribute] = sym_attribute,
  [sym_attribute_keyword] = sym_attribute_keyword,
  [sym_inline_ref] = sym_inline_ref,
  [sym_ref_definition] = sym_ref_definition,
  [sym_ref_path] = sym_ref_path,
  [sym_enum_definition] = sym_enum_definition,
  [sym_enum_value] = sym_enum_value,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_table_definition_repeat1] = aux_sym_table_definition_repeat1,
  [aux_sym_attribute_block_repeat1] = aux_sym_attribute_block_repeat1,
  [aux_sym_enum_definition_repeat1] = aux_sym_enum_definition_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_Table] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pk] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unique] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_increment] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_notnull] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Ref] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ref] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_inline_ref_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Enum] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_table_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_column_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_block] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_ref_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_ref_path] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_table_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attribute_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_direction = 1,
  field_from = 2,
  field_name = 3,
  field_op = 4,
  field_target_table = 5,
  field_to = 6,
  field_type = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_direction] = "direction",
  [field_from] = "from",
  [field_name] = "name",
  [field_op] = "op",
  [field_target_table] = "target_table",
  [field_to] = "to",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 3},
  [4] = {.index = 6, .length = 2},
  [5] = {.index = 8, .length = 2},
  [6] = {.index = 10, .length = 2},
  [7] = {.index = 12, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 0},
    {field_type, 1},
  [3] =
    {field_from, 2},
    {field_op, 3},
    {field_to, 4},
  [6] =
    {field_direction, 2},
    {field_target_table, 3},
  [8] =
    {field_direction, 3},
    {field_target_table, 4},
  [10] =
    {field_direction, 2},
    {field_target_table, 4},
  [12] =
    {field_direction, 3},
    {field_target_table, 5},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(35);
      ADVANCE_MAP(
        '#', 36,
        ',', 41,
        '-', 53,
        '.', 54,
        '/', 3,
        ':', 49,
        '<', 52,
        '>', 51,
        'E', 22,
        'R', 7,
        'T', 4,
        '[', 40,
        ']', 42,
        'i', 23,
        'n', 27,
        'p', 16,
        'r', 10,
        'u', 24,
        '{', 38,
        '}', 39,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(26);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(36);
      if (lookahead == ',') ADVANCE(41);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '[') ADVANCE(40);
      if (lookahead == '}') ADVANCE(39);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(36);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == 'b') ADVANCE(18);
      END_STATE();
    case 6:
      if (lookahead == 'c') ADVANCE(29);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 13:
      if (lookahead == 'f') ADVANCE(47);
      END_STATE();
    case 14:
      if (lookahead == 'f') ADVANCE(48);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(28);
      END_STATE();
    case 16:
      if (lookahead == 'k') ADVANCE(43);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(46);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 20:
      if (lookahead == 'm') ADVANCE(55);
      END_STATE();
    case 21:
      if (lookahead == 'm') ADVANCE(12);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(32);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(31);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(33);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 28:
      if (lookahead == 'q') ADVANCE(34);
      END_STATE();
    case 29:
      if (lookahead == 'r') ADVANCE(11);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(1);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(45);
      END_STATE();
    case 32:
      if (lookahead == 'u') ADVANCE(20);
      END_STATE();
    case 33:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 34:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_Table);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_pk);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_unique);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_increment);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_notnull);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_Ref);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_ref);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_inline_ref_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_Enum);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 50},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 50},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 50},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_Table] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_pk] = ACTIONS(1),
    [anon_sym_unique] = ACTIONS(1),
    [anon_sym_increment] = ACTIONS(1),
    [anon_sym_notnull] = ACTIONS(1),
    [anon_sym_Ref] = ACTIONS(1),
    [anon_sym_ref] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_Enum] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(52),
    [sym_table_definition] = STATE(3),
    [sym_ref_definition] = STATE(3),
    [sym_enum_definition] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_Table] = ACTIONS(7),
    [anon_sym_Ref] = ACTIONS(9),
    [anon_sym_ref] = ACTIONS(9),
    [anon_sym_Enum] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 10,
      ts_builtin_sym_end,
      anon_sym_Table,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_Ref,
      anon_sym_ref,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DASH,
      anon_sym_Enum,
  [16] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_Table,
    ACTIONS(11), 1,
      anon_sym_Enum,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(9), 2,
      anon_sym_Ref,
      anon_sym_ref,
    STATE(4), 4,
      sym_table_definition,
      sym_ref_definition,
      sym_enum_definition,
      aux_sym_source_file_repeat1,
  [39] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      anon_sym_Table,
    ACTIONS(25), 1,
      anon_sym_Enum,
    ACTIONS(22), 2,
      anon_sym_Ref,
      anon_sym_ref,
    STATE(4), 4,
      sym_table_definition,
      sym_ref_definition,
      sym_enum_definition,
      aux_sym_source_file_repeat1,
  [62] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(23), 1,
      sym_attribute,
    ACTIONS(30), 2,
      anon_sym_Ref,
      anon_sym_ref,
    STATE(30), 2,
      sym_attribute_keyword,
      sym_inline_ref,
    ACTIONS(28), 4,
      anon_sym_pk,
      anon_sym_unique,
      anon_sym_increment,
      anon_sym_notnull,
  [83] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(36), 1,
      sym_attribute,
    ACTIONS(30), 2,
      anon_sym_Ref,
      anon_sym_ref,
    STATE(30), 2,
      sym_attribute_keyword,
      sym_inline_ref,
    ACTIONS(28), 4,
      anon_sym_pk,
      anon_sym_unique,
      anon_sym_increment,
      anon_sym_notnull,
  [104] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(32), 5,
      ts_builtin_sym_end,
      anon_sym_Table,
      anon_sym_Ref,
      anon_sym_ref,
      anon_sym_Enum,
  [115] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(34), 5,
      ts_builtin_sym_end,
      anon_sym_Table,
      anon_sym_Ref,
      anon_sym_ref,
      anon_sym_Enum,
  [126] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(36), 5,
      ts_builtin_sym_end,
      anon_sym_Table,
      anon_sym_Ref,
      anon_sym_ref,
      anon_sym_Enum,
  [137] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(38), 5,
      ts_builtin_sym_end,
      anon_sym_Table,
      anon_sym_Ref,
      anon_sym_ref,
      anon_sym_Enum,
  [148] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(40), 5,
      ts_builtin_sym_end,
      anon_sym_Table,
      anon_sym_Ref,
      anon_sym_ref,
      anon_sym_Enum,
  [159] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 1,
      anon_sym_RBRACE,
    ACTIONS(44), 1,
      sym_identifier,
    STATE(13), 2,
      sym_enum_value,
      aux_sym_enum_definition_repeat1,
  [173] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(44), 1,
      sym_identifier,
    ACTIONS(46), 1,
      anon_sym_RBRACE,
    STATE(18), 2,
      sym_enum_value,
      aux_sym_enum_definition_repeat1,
  [187] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 1,
      anon_sym_RBRACE,
    ACTIONS(50), 1,
      sym_identifier,
    STATE(15), 2,
      sym_column_definition,
      aux_sym_table_definition_repeat1,
  [201] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      sym_identifier,
    ACTIONS(52), 1,
      anon_sym_RBRACE,
    STATE(17), 2,
      sym_column_definition,
      aux_sym_table_definition_repeat1,
  [215] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    STATE(29), 1,
      sym_attribute_block,
    ACTIONS(54), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [229] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      anon_sym_RBRACE,
    ACTIONS(60), 1,
      sym_identifier,
    STATE(17), 2,
      sym_column_definition,
      aux_sym_table_definition_repeat1,
  [243] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      anon_sym_RBRACE,
    ACTIONS(65), 1,
      sym_identifier,
    STATE(18), 2,
      sym_enum_value,
      aux_sym_enum_definition_repeat1,
  [257] = 3,
    ACTIONS(68), 1,
      sym_comment,
    ACTIONS(70), 1,
      aux_sym_inline_ref_token1,
    ACTIONS(72), 3,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DASH,
  [269] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 3,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DASH,
  [278] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_COMMA,
    ACTIONS(76), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [289] = 4,
    ACTIONS(68), 1,
      sym_comment,
    ACTIONS(80), 1,
      aux_sym_inline_ref_token1,
    ACTIONS(82), 1,
      sym_identifier,
    STATE(40), 1,
      sym_ref_path,
  [302] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 1,
      anon_sym_COMMA,
    ACTIONS(86), 1,
      anon_sym_RBRACK,
    STATE(24), 1,
      aux_sym_attribute_block_repeat1,
  [315] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 1,
      anon_sym_COMMA,
    ACTIONS(88), 1,
      anon_sym_RBRACK,
    STATE(27), 1,
      aux_sym_attribute_block_repeat1,
  [328] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 3,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DASH,
  [337] = 4,
    ACTIONS(68), 1,
      sym_comment,
    ACTIONS(82), 1,
      sym_identifier,
    ACTIONS(92), 1,
      aux_sym_inline_ref_token1,
    STATE(35), 1,
      sym_ref_path,
  [350] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_COMMA,
    ACTIONS(97), 1,
      anon_sym_RBRACK,
    STATE(27), 1,
      aux_sym_attribute_block_repeat1,
  [363] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [371] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [379] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [387] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [395] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [403] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(11), 1,
      sym_ref_path,
  [413] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [421] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [429] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [437] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(42), 1,
      sym_ref_path,
  [447] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(20), 1,
      sym_ref_path,
  [457] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(41), 1,
      sym_ref_path,
  [467] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [475] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [483] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [491] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      anon_sym_LBRACE,
  [498] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      sym_identifier,
  [505] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_COLON,
  [512] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      sym_identifier,
  [519] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_DOT,
  [526] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      sym_identifier,
  [533] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_LBRACE,
  [540] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      sym_identifier,
  [547] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 1,
      anon_sym_COLON,
  [554] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 16,
  [SMALL_STATE(4)] = 39,
  [SMALL_STATE(5)] = 62,
  [SMALL_STATE(6)] = 83,
  [SMALL_STATE(7)] = 104,
  [SMALL_STATE(8)] = 115,
  [SMALL_STATE(9)] = 126,
  [SMALL_STATE(10)] = 137,
  [SMALL_STATE(11)] = 148,
  [SMALL_STATE(12)] = 159,
  [SMALL_STATE(13)] = 173,
  [SMALL_STATE(14)] = 187,
  [SMALL_STATE(15)] = 201,
  [SMALL_STATE(16)] = 215,
  [SMALL_STATE(17)] = 229,
  [SMALL_STATE(18)] = 243,
  [SMALL_STATE(19)] = 257,
  [SMALL_STATE(20)] = 269,
  [SMALL_STATE(21)] = 278,
  [SMALL_STATE(22)] = 289,
  [SMALL_STATE(23)] = 302,
  [SMALL_STATE(24)] = 315,
  [SMALL_STATE(25)] = 328,
  [SMALL_STATE(26)] = 337,
  [SMALL_STATE(27)] = 350,
  [SMALL_STATE(28)] = 363,
  [SMALL_STATE(29)] = 371,
  [SMALL_STATE(30)] = 379,
  [SMALL_STATE(31)] = 387,
  [SMALL_STATE(32)] = 395,
  [SMALL_STATE(33)] = 403,
  [SMALL_STATE(34)] = 413,
  [SMALL_STATE(35)] = 421,
  [SMALL_STATE(36)] = 429,
  [SMALL_STATE(37)] = 437,
  [SMALL_STATE(38)] = 447,
  [SMALL_STATE(39)] = 457,
  [SMALL_STATE(40)] = 467,
  [SMALL_STATE(41)] = 475,
  [SMALL_STATE(42)] = 483,
  [SMALL_STATE(43)] = 491,
  [SMALL_STATE(44)] = 498,
  [SMALL_STATE(45)] = 505,
  [SMALL_STATE(46)] = 512,
  [SMALL_STATE(47)] = 519,
  [SMALL_STATE(48)] = 526,
  [SMALL_STATE(49)] = 533,
  [SMALL_STATE(50)] = 540,
  [SMALL_STATE(51)] = 547,
  [SMALL_STATE(52)] = 554,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref_path, 3, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_definition, 5, 0, 1),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_definition, 4, 0, 1),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_definition, 4, 0, 1),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_definition, 5, 0, 1),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref_definition, 5, 0, 3),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_definition, 2, 0, 2),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_table_definition_repeat1, 2, 0, 0),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_table_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_definition_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_value, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attribute_block_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_attribute_block_repeat1, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_value, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_definition, 3, 0, 2),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_keyword, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_block, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_block, 4, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_ref, 4, 0, 4),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_ref, 5, 0, 5),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_ref, 5, 0, 6),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_ref, 6, 0, 7),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [139] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_dbml(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "dbml",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
