/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 57
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  anon_sym_Table = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_LBRACK = 5,
  anon_sym_COMMA = 6,
  anon_sym_RBRACK = 7,
  anon_sym_pk = 8,
  anon_sym_unique = 9,
  anon_sym_not = 10,
  anon_sym_null = 11,
  anon_sym_increment = 12,
  anon_sym_notnull = 13,
  anon_sym_Indexes = 14,
  anon_sym_LPAREN = 15,
  anon_sym_RPAREN = 16,
  anon_sym_Ref = 17,
  anon_sym_COLON = 18,
  anon_sym_GT = 19,
  anon_sym_LT = 20,
  anon_sym_DASH = 21,
  anon_sym_DOT = 22,
  anon_sym_Enum = 23,
  sym_identifier = 24,
  sym_source_file = 25,
  sym_table_definition = 26,
  sym_column_definition = 27,
  sym_attribute_block = 28,
  sym_attribute = 29,
  sym_index_block = 30,
  sym_index_definition = 31,
  sym_ref_definition = 32,
  sym_ref_path = 33,
  sym_enum_definition = 34,
  sym_enum_value = 35,
  aux_sym_source_file_repeat1 = 36,
  aux_sym_table_definition_repeat1 = 37,
  aux_sym_attribute_block_repeat1 = 38,
  aux_sym_index_block_repeat1 = 39,
  aux_sym_index_definition_repeat1 = 40,
  aux_sym_enum_definition_repeat1 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_Table] = "Table",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_pk] = "pk",
  [anon_sym_unique] = "unique",
  [anon_sym_not] = "not",
  [anon_sym_null] = "null",
  [anon_sym_increment] = "increment",
  [anon_sym_notnull] = "not null",
  [anon_sym_Indexes] = "Indexes",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_Ref] = "Ref",
  [anon_sym_COLON] = ":",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_DASH] = "-",
  [anon_sym_DOT] = ".",
  [anon_sym_Enum] = "Enum",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym_table_definition] = "table_definition",
  [sym_column_definition] = "column_definition",
  [sym_attribute_block] = "attribute_block",
  [sym_attribute] = "attribute",
  [sym_index_block] = "index_block",
  [sym_index_definition] = "index_definition",
  [sym_ref_definition] = "ref_definition",
  [sym_ref_path] = "ref_path",
  [sym_enum_definition] = "enum_definition",
  [sym_enum_value] = "enum_value",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_table_definition_repeat1] = "table_definition_repeat1",
  [aux_sym_attribute_block_repeat1] = "attribute_block_repeat1",
  [aux_sym_index_block_repeat1] = "index_block_repeat1",
  [aux_sym_index_definition_repeat1] = "index_definition_repeat1",
  [aux_sym_enum_definition_repeat1] = "enum_definition_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_Table] = anon_sym_Table,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_pk] = anon_sym_pk,
  [anon_sym_unique] = anon_sym_unique,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_null] = anon_sym_null,
  [anon_sym_increment] = anon_sym_increment,
  [anon_sym_notnull] = anon_sym_notnull,
  [anon_sym_Indexes] = anon_sym_Indexes,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_Ref] = anon_sym_Ref,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_Enum] = anon_sym_Enum,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym_table_definition] = sym_table_definition,
  [sym_column_definition] = sym_column_definition,
  [sym_attribute_block] = sym_attribute_block,
  [sym_attribute] = sym_attribute,
  [sym_index_block] = sym_index_block,
  [sym_index_definition] = sym_index_definition,
  [sym_ref_definition] = sym_ref_definition,
  [sym_ref_path] = sym_ref_path,
  [sym_enum_definition] = sym_enum_definition,
  [sym_enum_value] = sym_enum_value,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_table_definition_repeat1] = aux_sym_table_definition_repeat1,
  [aux_sym_attribute_block_repeat1] = aux_sym_attribute_block_repeat1,
  [aux_sym_index_block_repeat1] = aux_sym_index_block_repeat1,
  [aux_sym_index_definition_repeat1] = aux_sym_index_definition_repeat1,
  [aux_sym_enum_definition_repeat1] = aux_sym_enum_definition_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_Table] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pk] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unique] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_null] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_increment] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_notnull] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Indexes] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Ref] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Enum] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_table_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_column_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_block] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_index_block] = {
    .visible = true,
    .named = true,
  },
  [sym_index_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_ref_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_ref_path] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_table_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attribute_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_index_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_index_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_from = 1,
  field_name = 2,
  field_op = 3,
  field_to = 4,
  field_type = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_from] = "from",
  [field_name] = "name",
  [field_op] = "op",
  [field_to] = "to",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 0},
    {field_type, 1},
  [3] =
    {field_from, 2},
    {field_op, 3},
    {field_to, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(41);
      ADVANCE_MAP(
        '#', 42,
        '(', 57,
        ')', 58,
        ',', 47,
        '-', 63,
        '.', 64,
        '/', 3,
        ':', 60,
        '<', 62,
        '>', 61,
        'E', 25,
        'I', 26,
        'R', 8,
        'T', 4,
        '[', 46,
        ']', 48,
        'i', 27,
        'n', 31,
        'p', 17,
        'u', 28,
        '{', 44,
        '}', 45,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(42);
      if (lookahead == '(') ADVANCE(57);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == 'I') ADVANCE(69);
      if (lookahead == '[') ADVANCE(46);
      if (lookahead == '}') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(42);
      if (lookahead == ',') ADVANCE(47);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '}') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(42);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == 'b') ADVANCE(20);
      END_STATE();
    case 6:
      if (lookahead == 'c') ADVANCE(33);
      END_STATE();
    case 7:
      if (lookahead == 'd') ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 15:
      if (lookahead == 'f') ADVANCE(59);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(32);
      END_STATE();
    case 17:
      if (lookahead == 'k') ADVANCE(49);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(52);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(54);
      END_STATE();
    case 20:
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(18);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(19);
      END_STATE();
    case 23:
      if (lookahead == 'm') ADVANCE(65);
      END_STATE();
    case 24:
      if (lookahead == 'm') ADVANCE(14);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(37);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 28:
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 29:
      if (lookahead == 'n') ADVANCE(36);
      END_STATE();
    case 30:
      if (lookahead == 'n') ADVANCE(39);
      END_STATE();
    case 31:
      if (lookahead == 'o') ADVANCE(35);
      if (lookahead == 'u') ADVANCE(21);
      END_STATE();
    case 32:
      if (lookahead == 'q') ADVANCE(38);
      END_STATE();
    case 33:
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 34:
      if (lookahead == 's') ADVANCE(55);
      END_STATE();
    case 35:
      if (lookahead == 't') ADVANCE(51);
      END_STATE();
    case 36:
      if (lookahead == 't') ADVANCE(53);
      END_STATE();
    case 37:
      if (lookahead == 'u') ADVANCE(23);
      END_STATE();
    case 38:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 39:
      if (lookahead == 'u') ADVANCE(22);
      END_STATE();
    case 40:
      if (lookahead == 'x') ADVANCE(11);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_Table);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_pk);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_unique);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_not);
      if (lookahead == ' ') ADVANCE(30);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_null);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_increment);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_notnull);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_Indexes);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_Indexes);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_Ref);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_Enum);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'x') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_Table] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_pk] = ACTIONS(1),
    [anon_sym_unique] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_null] = ACTIONS(1),
    [anon_sym_increment] = ACTIONS(1),
    [anon_sym_notnull] = ACTIONS(1),
    [anon_sym_Indexes] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_Ref] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_Enum] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(46),
    [sym_table_definition] = STATE(2),
    [sym_ref_definition] = STATE(2),
    [sym_enum_definition] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_Table] = ACTIONS(7),
    [anon_sym_Ref] = ACTIONS(9),
    [anon_sym_Enum] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_Table,
    ACTIONS(9), 1,
      anon_sym_Ref,
    ACTIONS(11), 1,
      anon_sym_Enum,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    STATE(3), 4,
      sym_table_definition,
      sym_ref_definition,
      sym_enum_definition,
      aux_sym_source_file_repeat1,
  [22] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      anon_sym_Table,
    ACTIONS(20), 1,
      anon_sym_Ref,
    ACTIONS(23), 1,
      anon_sym_Enum,
    STATE(3), 4,
      sym_table_definition,
      sym_ref_definition,
      sym_enum_definition,
      aux_sym_source_file_repeat1,
  [44] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(26), 7,
      ts_builtin_sym_end,
      anon_sym_Table,
      anon_sym_Ref,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DASH,
      anon_sym_Enum,
  [57] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(30), 1,
      anon_sym_not,
    STATE(43), 1,
      sym_attribute,
    ACTIONS(28), 5,
      anon_sym_pk,
      anon_sym_unique,
      anon_sym_null,
      anon_sym_increment,
      anon_sym_notnull,
  [74] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(30), 1,
      anon_sym_not,
    STATE(33), 1,
      sym_attribute,
    ACTIONS(28), 5,
      anon_sym_pk,
      anon_sym_unique,
      anon_sym_null,
      anon_sym_increment,
      anon_sym_notnull,
  [91] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(32), 1,
      anon_sym_RBRACE,
    ACTIONS(34), 1,
      anon_sym_Indexes,
    ACTIONS(36), 1,
      sym_identifier,
    STATE(8), 3,
      sym_column_definition,
      sym_index_block,
      aux_sym_table_definition_repeat1,
  [109] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(34), 1,
      anon_sym_Indexes,
    ACTIONS(36), 1,
      sym_identifier,
    ACTIONS(38), 1,
      anon_sym_RBRACE,
    STATE(9), 3,
      sym_column_definition,
      sym_index_block,
      aux_sym_table_definition_repeat1,
  [127] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(40), 1,
      anon_sym_RBRACE,
    ACTIONS(42), 1,
      anon_sym_Indexes,
    ACTIONS(45), 1,
      sym_identifier,
    STATE(9), 3,
      sym_column_definition,
      sym_index_block,
      aux_sym_table_definition_repeat1,
  [145] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 1,
      anon_sym_RBRACE,
    ACTIONS(50), 1,
      anon_sym_LBRACK,
    STATE(28), 1,
      sym_attribute_block,
    ACTIONS(52), 2,
      anon_sym_Indexes,
      sym_identifier,
  [162] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 4,
      ts_builtin_sym_end,
      anon_sym_Table,
      anon_sym_Ref,
      anon_sym_Enum,
  [172] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 2,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
    ACTIONS(58), 2,
      anon_sym_Indexes,
      sym_identifier,
  [184] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      anon_sym_RBRACE,
    ACTIONS(62), 1,
      sym_identifier,
    STATE(16), 2,
      sym_enum_value,
      aux_sym_enum_definition_repeat1,
  [198] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 4,
      ts_builtin_sym_end,
      anon_sym_Table,
      anon_sym_Ref,
      anon_sym_Enum,
  [208] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 4,
      ts_builtin_sym_end,
      anon_sym_Table,
      anon_sym_Ref,
      anon_sym_Enum,
  [218] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      sym_identifier,
    ACTIONS(68), 1,
      anon_sym_RBRACE,
    STATE(25), 2,
      sym_enum_value,
      aux_sym_enum_definition_repeat1,
  [232] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_RBRACE,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    STATE(20), 2,
      sym_index_definition,
      aux_sym_index_block_repeat1,
  [246] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 4,
      ts_builtin_sym_end,
      anon_sym_Table,
      anon_sym_Ref,
      anon_sym_Enum,
  [256] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 4,
      ts_builtin_sym_end,
      anon_sym_Table,
      anon_sym_Ref,
      anon_sym_Enum,
  [266] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(78), 1,
      anon_sym_RBRACE,
    STATE(21), 2,
      sym_index_definition,
      aux_sym_index_block_repeat1,
  [280] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_RBRACE,
    ACTIONS(82), 1,
      anon_sym_LPAREN,
    STATE(21), 2,
      sym_index_definition,
      aux_sym_index_block_repeat1,
  [294] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      anon_sym_LBRACK,
    STATE(39), 1,
      sym_attribute_block,
    ACTIONS(85), 2,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
  [308] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 2,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
    ACTIONS(89), 2,
      anon_sym_Indexes,
      sym_identifier,
  [320] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      anon_sym_LBRACK,
    STATE(44), 1,
      sym_attribute_block,
    ACTIONS(91), 2,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
  [334] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_RBRACE,
    ACTIONS(95), 1,
      sym_identifier,
    STATE(25), 2,
      sym_enum_value,
      aux_sym_enum_definition_repeat1,
  [348] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 3,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_DASH,
  [357] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 1,
      anon_sym_RBRACE,
    ACTIONS(102), 2,
      anon_sym_Indexes,
      sym_identifier,
  [368] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_RBRACE,
    ACTIONS(106), 2,
      anon_sym_Indexes,
      sym_identifier,
  [379] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_COMMA,
    ACTIONS(110), 1,
      anon_sym_RPAREN,
    STATE(32), 1,
      aux_sym_index_definition_repeat1,
  [392] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      anon_sym_RBRACE,
    ACTIONS(114), 2,
      anon_sym_Indexes,
      sym_identifier,
  [403] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      anon_sym_COMMA,
    ACTIONS(116), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [414] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_COMMA,
    ACTIONS(120), 1,
      anon_sym_RPAREN,
    STATE(35), 1,
      aux_sym_index_definition_repeat1,
  [427] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      anon_sym_COMMA,
    ACTIONS(124), 1,
      anon_sym_RBRACK,
    STATE(34), 1,
      aux_sym_attribute_block_repeat1,
  [440] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      anon_sym_COMMA,
    ACTIONS(126), 1,
      anon_sym_RBRACK,
    STATE(36), 1,
      aux_sym_attribute_block_repeat1,
  [453] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 1,
      anon_sym_COMMA,
    ACTIONS(131), 1,
      anon_sym_RPAREN,
    STATE(35), 1,
      aux_sym_index_definition_repeat1,
  [466] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_COMMA,
    ACTIONS(136), 1,
      anon_sym_RBRACK,
    STATE(36), 1,
      aux_sym_attribute_block_repeat1,
  [479] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [487] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 1,
      sym_identifier,
    STATE(11), 1,
      sym_ref_path,
  [497] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 2,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
  [505] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [513] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 1,
      sym_identifier,
    STATE(26), 1,
      sym_ref_path,
  [523] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [531] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [539] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 2,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
  [547] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      anon_sym_COLON,
  [554] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      ts_builtin_sym_end,
  [561] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      sym_identifier,
  [568] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      sym_identifier,
  [575] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 1,
      anon_sym_LBRACE,
  [582] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      sym_identifier,
  [589] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      anon_sym_LBRACE,
  [596] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 1,
      sym_identifier,
  [603] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      anon_sym_LBRACE,
  [610] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      sym_identifier,
  [617] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 1,
      anon_sym_DOT,
  [624] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 22,
  [SMALL_STATE(4)] = 44,
  [SMALL_STATE(5)] = 57,
  [SMALL_STATE(6)] = 74,
  [SMALL_STATE(7)] = 91,
  [SMALL_STATE(8)] = 109,
  [SMALL_STATE(9)] = 127,
  [SMALL_STATE(10)] = 145,
  [SMALL_STATE(11)] = 162,
  [SMALL_STATE(12)] = 172,
  [SMALL_STATE(13)] = 184,
  [SMALL_STATE(14)] = 198,
  [SMALL_STATE(15)] = 208,
  [SMALL_STATE(16)] = 218,
  [SMALL_STATE(17)] = 232,
  [SMALL_STATE(18)] = 246,
  [SMALL_STATE(19)] = 256,
  [SMALL_STATE(20)] = 266,
  [SMALL_STATE(21)] = 280,
  [SMALL_STATE(22)] = 294,
  [SMALL_STATE(23)] = 308,
  [SMALL_STATE(24)] = 320,
  [SMALL_STATE(25)] = 334,
  [SMALL_STATE(26)] = 348,
  [SMALL_STATE(27)] = 357,
  [SMALL_STATE(28)] = 368,
  [SMALL_STATE(29)] = 379,
  [SMALL_STATE(30)] = 392,
  [SMALL_STATE(31)] = 403,
  [SMALL_STATE(32)] = 414,
  [SMALL_STATE(33)] = 427,
  [SMALL_STATE(34)] = 440,
  [SMALL_STATE(35)] = 453,
  [SMALL_STATE(36)] = 466,
  [SMALL_STATE(37)] = 479,
  [SMALL_STATE(38)] = 487,
  [SMALL_STATE(39)] = 497,
  [SMALL_STATE(40)] = 505,
  [SMALL_STATE(41)] = 513,
  [SMALL_STATE(42)] = 523,
  [SMALL_STATE(43)] = 531,
  [SMALL_STATE(44)] = 539,
  [SMALL_STATE(45)] = 547,
  [SMALL_STATE(46)] = 554,
  [SMALL_STATE(47)] = 561,
  [SMALL_STATE(48)] = 568,
  [SMALL_STATE(49)] = 575,
  [SMALL_STATE(50)] = 582,
  [SMALL_STATE(51)] = 589,
  [SMALL_STATE(52)] = 596,
  [SMALL_STATE(53)] = 603,
  [SMALL_STATE(54)] = 610,
  [SMALL_STATE(55)] = 617,
  [SMALL_STATE(56)] = 624,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref_path, 3, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [30] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [34] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_table_definition_repeat1, 2, 0, 0),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_table_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_table_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_definition, 2, 0, 2),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_column_definition, 2, 0, 2),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref_definition, 5, 0, 3),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_block, 4, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute_block, 4, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_definition, 4, 0, 1),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_definition, 4, 0, 1),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_definition, 5, 0, 1),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_definition, 5, 0, 1),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_index_block_repeat1, 2, 0, 0),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_index_block_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_index_definition, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_block, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute_block, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_index_definition, 4, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_definition_repeat1, 2, 0, 0),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_index_block, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_index_block, 3, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_definition, 3, 0, 2),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_column_definition, 3, 0, 2),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_index_block, 4, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_index_block, 4, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_value, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [128] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_index_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_index_definition_repeat1, 2, 0, 0),
  [133] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attribute_block_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_attribute_block_repeat1, 2, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_value, 2, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_index_definition, 5, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [148] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_dbml(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "dbml",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
